title: Microgrid Operations Control Center
categories:
  - Frontend Development
  - 3D Modeling
  - Data Visualization
  - UI
  - UX
sections:
  - type: notes
    attributes:
      content: '@blurb.md'
      image: '@MOC.png'
      caption: caption here
      company: CleanSpark
      overview:
        - title: Title
          message: Microgrid Operations Control Center
        - title: Company
          message: CleanSpark
        - title: Technology
          message: SCALA, Play Framework, HTML, SCSS, Gulp.js, SketchUp
        - title: Roles
          message: 3D Modeling, Wireframes, Interface Design, Visual Concepts, User Research, Front-End Development
  - type: centered-quote
    attributes:
      content: An Ambitious Vision
  - type: centered-text
    attributes:
      content: '@blurb3.md'
  - type: two-images
    attributes:
      left: sketch1.png
      captionLT: Room diagram v1
      right: sketch2.png
      captionRT: Room diagram v2
  - type: image-text
    attributes:
      header: 3D Model
      paragraphs:
        - Maximize floor space with mounted large screens, and a curved desk along the perimeter;
        - In front of the main display, create an area large enough for one individual to interact with the screen where others could watch without disrupting the sensors; LED ticker made from an Arduino across the top  of the room to view realtime energy usage across all portfolios; Cabinet space underneath the desk for server racks
      image: 3dModel.png
  - type: centered-text
    attributes:
      content: '@blurb5.md'
  - type: two-images
    attributes:
      left: '@fractalGrid1.jpg'
      captionLT: 'FractalGrid: one site, multiple facilities'
      right: '@fractalGrid2.jpg'
      captionRT: 'FractalGrid: multiple sites'
  - type: centered-text
    attributes:
      content: '@blurb8.md'
  - type: image-full
    attributes:
      image: '@nodeView.png'
  - type: centered-text
    attributes:
      content: '@blurb6.md'
  - type: image-full
    attributes:
      image: '@CampPendleton-FractalGrid.mp4'
      content: '@blurb7.md'